### ISSUE TITLE
Datafield names changed after upgrade to API V2

### ISSUE THREAD

**Issue by ExtremeEmpress** [ExtremeEmpress/ouradb#4]
Looks like Oura has changed the field names for some values between API V1 and V2.

Some examples:
- "awake" in API V1 is "awake_time" in API V2
- "breath_average" in API V1 is "average_breath" in API V2
- "deep", "light" in API V1 are "deep_sleep_duration", "light_sleep_duration" in API V2

Probably there are more. 

This means that after changing to V2, the values posted to database will change. Long time tracking will suffer when performing the change. 

It is an unfortunate decision from Oura to change the field names from one API version to another and lose consistency. But I am not sure if this should be fixed in the scripts. I would prefer using the field names that Oura themselves use in the scripts.

Still, I would personally like to have data consistency over naming consistency, as I have now pushed the data into a database for a long while. So perhaps an optional field name convertor function should be added into oura_post_to_influxdb.py, which can be used if moving from using API V1 to using API V2.

**Comment by praxis88** [comment]
The easiest way to do this would probably be to make an v1 to v2 script that queries influxdb for these and re-injects them back into influxdb under the new name. You'd have duplicate data under 2 names for that time period, but that's no big deal really. You might even be able to destroy the data under the old name once verifying it moved successfully

**Comment by praxis88** [comment]
I started working on it this morning, and it occurred to me, you can just delete the original database, or start a new one beside it and query the whole thing from oura with the v2 api. The data underneath is the same, its just outwardly exposed in different ways by different apis

**Comment by ExtremeEmpress** [comment]
You are right! I think that is the best solution for this. I will close the issue.
